name: "Terraform & Ansible CI"
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform fmt -check || true
        working-directory: ./terraform
      - run: terraform init
        working-directory: ./terraform
      - run: terraform validate
        working-directory: ./terraform
      - uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform
          framework: terraform
          soft_fail: true
      - uses: ansible/ansible-lint@main
        with:
          args: "./ansible/update_lambda.yml"
