name: "Terraform & Ansible CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform_and_ansible:
    name: "Validate Infrastructure & Ansible"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "latest"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3
          role-to-assume: arn:aws:iam::738563260931:role/role_etudiants
          role-duration-seconds: 1200

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./terraform

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Build Lambda Zip
        run: zip -r lambda_function.zip .
        working-directory: ./src

      - name: Terraform Plan
        run: terraform plan -no-color
        working-directory: ./terraform

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply -auto-approve -no-color
        working-directory: ./terraform

      - name: Checkov Security Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./terraform
          framework: terraform
          soft_fail: true

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
          
      - name: Infracost Breakdown
        run: infracost breakdown --path ./terraform
        continue-on-error: true

      - name: Run Ansible Lint
        uses: ansible/ansible-lint@main
        with:
          targets: "./ansible/update_lambda.yml"
